# Generated by Django 4.0.4 on 2024-05-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_choice_question_quiz_quizattempt_useranswer_and_more'),
        ('base', '0004_player'),
    ]

    operations = [
    ]
